### ISSUE TITLE
Why was concurrent extraction removed?

### ISSUE THREAD

**Issue by alexchandel** [rgov/starter-pack#11]
Concurrent extraction was added long ago in fc0c0076e0336e1828b87dd1162852bedf33ffe7.  Why was it removed in f004f65a8b8ce8312a7e2eed0d7fcb8d5578709c?

The commit claimed to "fix some bugs," which I assume were something related to preserving symlinks and splitting newlines.  But I can't see any impetus for removing parallel extraction.

**Comment by alexchandel** [comment]
Similarly, what's the purpose of "Add subcomponents of Dwarf Fortress" e38f4030bd834eb8266539a800de98efdad68c34?  Just to work around a feature regression?

**Comment by rgov** [comment]
I removed parallelism probably because I was debugging something that failed and it made it easier. I’m of the opinion that concurrency isn’t a great feature here. There are two scenarios:

(1) The script is working fine and the user is producing a new starter pack. This is only done occasionally and so the amount of time taken for a modern system to unzip a handful of packages is not really a significant burden. 

(2) The starter pack build script is being debugged. This is a case where concurrency and optimization needs to be disabled. Backtraces should be clear without indirection.

**Comment by rgov** [comment]
I can’t recall the e38f403 fix—bad commit message, sorry—but it looks like maybe that I am explicitly listing a subset of components? Maybe there was one that didn’t extract properly?
